Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Auth Token Methods
  post '/auth/token' => 'login#create'
  post '/auth/refresh' => 'login#refresh'
  get '/auth/token' => 'login#validate'
  post '/auth/send_reset' => 'login#send_reset_password'
  patch '/auth/reset' => 'login#reset_password'

  # Contacts Methods
  get '/contacts/number_types' => 'contacts#get_number_types'
  get '/contacts/address_types' => 'contacts#get_address_types'
  get '/contacts/domain' => 'contacts#get_by_domain'
  get '/contacts' => 'contacts#get_by_user'
  post '/contacts' => 'contacts#create'
  get '/contacts/:id' => 'contacts#get_by_id'
  delete '/contacts/:id' => 'contacts#delete'
  patch '/contacts/:id' => 'contacts#update'
  # Call Record Methods
  get '/cdrs' => 'call_record#get_by_user'
  get '/domain_cdrs' => 'call_record#get_by_domain'
  # Voicemail Methods
  get '/voicemails' => 'voicemail#get_by_user'
  patch '/voicemails/:id' => 'voicemail#update'
  delete '/voicemails/:id' => 'voicemail#delete'
  get '/voicemails/:id/voice_payload' => 'voicemail#voice_payload'
  get '/voicemails/:id/fax_payload' => 'voicemail#fax_payload'
  post '/voicemails' => 'voicemail#create'
  get '/voicemails/count' => 'voicemail#message_count'
  post '/voicemails/fax' => 'voicemail#submit_fax'
  # Mailbox Methods
  get '/mailboxes' => 'mailbox#get_mailbox_summary'
  patch '/mailboxes' => 'mailbox#update_mailbox_summary'
  get '/mailboxes/greeting' => 'mailbox#get_greeting'
  patch '/mailboxes/greeting' => 'mailbox#update_greeting'
  # PBX My Phone Methods
  get '/myphones' => 'pbx_my_phone#get_by_user'
  patch '/myphones' => 'pbx_my_phone#update'
  get '/myphones/forward' => 'pbx_my_phone#get_forward_behaviors'
  get '/myphones/oncall' => 'pbx_my_phone#get_oncall_behaviors'
  post '/myphones/password' => 'pbx_my_phone#update_password'
  post '/myphones/schedule' => 'pbx_my_phone#schedule_create'
  patch '/myphones/schedule/:pbx_user_schedule_id' => 'pbx_my_phone#schedule_update'
  delete '/myphones/schedule/:pbx_user_schedule_id' => 'pbx_my_phone#schedule_delete'
  # PBX Phone Numbers Methods
  get '/phonenumbers' => 'pbx_phone_number#get_by_user'
  patch '/phonenumbers' => 'pbx_phone_number#update'
  get '/phonenumbers/ring' => 'pbx_phone_number#get_distinctive_ring'
  get '/phonenumbers/ext' => 'pbx_phone_number#get_extensions'
  get '/phonenumbers/loc' => 'pbx_phone_number#get_locations'
  get '/phonenumbers/actions' => 'pbx_phone_number#get_rule_actions'
  # PBX User Methods
  get '/pbxusers' => 'pbx_user#get_by_user'
  post '/pbxusers' => 'pbx_user#create'
  patch '/pbxusers' => 'pbx_user#update'
  delete '/pbxusers/:id' => 'pbx_user#delete'
  get '/pbxusers/forward' => 'pbx_user#get_forward_behaviors'
  get '/pbxusers/oncall' => 'pbx_user#get_oncall_behaviors'
  get '/pbxusers/fax_extensions' => 'pbx_user#fax_extensions'
  get '/pbxusers/mailboxes' => 'pbx_user#mailboxes'
  get '/pbxusers/roles' => 'pbx_user#roles'
  get '/pbxusers/locations' => 'pbx_user#locations'
  # PBX Location Methods
  get '/pbxlocations' => 'pbx_location#get_by_user'
  post '/pbxlocations' => 'pbx_location#create'
  patch '/pbxlocations' => 'pbx_location#update'
  delete '/pbxlocations/:id' => 'pbx_location#delete'
  # PBX Media File Methods
  get '/pbxmediafiles' => 'pbx_media_file#get_by_user'
  post '/pbxmediafiles' => 'pbx_media_file#create'
  patch '/pbxmediafiles' => 'pbx_media_file#update'
  delete '/pbxmediafiles/:id' => 'pbx_media_file#delete'
  get '/pbxmediafiles/:id/media' => 'pbx_media_file#get_media'
  # PBX Fax Methods
  get '/pbxfaxes' => 'pbx_fax#get_by_user'
  post '/pbxfaxes' => 'pbx_fax#create'
  patch '/pbxfaxes' => 'pbx_fax#update'
  delete '/pbxfaxes/:id' => 'pbx_fax#delete'
  get '/pbxfaxes/phonenumbers' => 'pbx_fax#get_phonenumbers'
  get '/pbxfaxes/formats' => 'pbx_fax#get_formats'
  get '/pbxfaxes/destination_types' => 'pbx_fax#get_destination_types'
  get '/pbxfaxes/mailboxes' => 'pbx_fax#get_mailboxes'
  # PBX Device Methods
  get '/pbxdevices' => 'pbx_device#get_by_user'
  post '/pbxdevices' => 'pbx_device#create'
  patch '/pbxdevices' => 'pbx_device#update'
  delete '/pbxdevices/:id' => 'pbx_device#delete'
  delete '/pbxdevices/:device_id/binding/:binding_id' => 'pbx_device#delete_binding'
  get '/pbxdevices/device_types' => 'pbx_device#device_types'
  get '/pbxdevices/device_signaling' => 'pbx_device#device_signaling'
  get '/pbxdevices/binding_types' => 'pbx_device#binding_types'
  get '/pbxdevices/binding_behaviors' => 'pbx_device#binding_behaviors'
  get '/pbxdevices/pbx_users' => 'pbx_device#pbx_users'
  get '/pbxdevices/pbx_parking_lots' => 'pbx_device#pbx_parking_lots'
  get '/pbxdevices/signaling' => 'pbx_device#signaling'
  # PBX Group Methods
  get '/pbxgroups' => 'pbx_group#get_by_user'
  post '/pbxgroups' => 'pbx_group#create'
  patch '/pbxgroups' => 'pbx_group#update'
  delete '/pbxgroups/:id' => 'pbx_group#delete_group'
  delete '/pbxgroups/:group_id/user/:user_id' => 'pbx_group#delete_group_user'
  get '/pbxgroups/ringtones' => 'pbx_group#ringtones'
  get '/pbxgroups/mailboxes' => 'pbx_group#mailboxes'
  get '/pbxgroups/pbx_users' => 'pbx_group#pbx_users'
  # PBX Parking Lot Methods
  get '/pbxparkinglots' => 'pbx_parking_lot#get_by_user'
  post '/pbxparkinglots' => 'pbx_parking_lot#create'
  patch '/pbxparkinglots' => 'pbx_parking_lot#update'
  delete '/pbxparkinglots/:id' => 'pbx_parking_lot#delete'
  get '/pbxparkinglots/moh' => 'pbx_parking_lot#moh'
  get '/pbxparkinglots/extensions' => 'pbx_parking_lot#extensions'
  # PBX On Call Methods
  get '/pbxoncalls' => 'pbx_on_call#get_by_user'
  get '/pbxoncalls/:pbx_oncall_id/:year/:month/pdf' => 'pbx_on_call#pdf'
  post '/pbxoncalls' => 'pbx_on_call#create'
  patch '/pbxoncalls' => 'pbx_on_call#update'
  delete '/pbxoncalls/:id' => 'pbx_on_call#delete'
  post '/pbxoncalls/:pbx_oncall_id/shifts' => 'pbx_on_call#shift_create'
  patch '/pbxoncalls/:pbx_oncall_id/shifts' => 'pbx_on_call#shift_update'
  delete '/pbxoncalls/:pbx_oncall_id/shifts/:id' => 'pbx_on_call#shift_delete'
  delete '/pbxoncalls/:pbx_oncall_id/shifts/:id/:user_id' => 'pbx_on_call#user_delete'
  get '/pbxoncalls/moh' => 'pbx_on_call#moh'
  get '/pbxoncalls/mediafiles' => 'pbx_on_call#mediafiles'
  get '/pbxoncalls/mailboxes' => 'pbx_on_call#mailboxes'
  get '/pbxoncalls/phonenumbers' => 'pbx_on_call#phonenumbers'
  get '/pbxoncalls/pbx_users' => 'pbx_on_call#pbx_users'
  get '/pbxoncalls/new' => 'pbx_on_call#get_new'
  # PBX Audit Log Methods
  get '/pbxaudits' => 'pbx_audit_log#get'
  # PBX Mailbox Admin
  get '/pbxmailboxes' => 'pbx_mailbox_admin#get'
  post '/pbxmailboxes' => 'pbx_mailbox_admin#create'
  patch '/pbxmailboxes' => 'pbx_mailbox_admin#update'
  delete '/pbxmailboxes/:id' => 'pbx_mailbox_admin#delete'
  get '/pbxmailboxes/:id/status' => 'pbx_mailbox_admin#get_status'
  get '/pbxmailboxes/:id/greeting' => 'pbx_mailbox_admin#get_greeting'
  patch '/pbxmailboxes/:id/greeting' => 'pbx_mailbox_admin#update_greeting'

  mount_ember_app :frontend, to: "/"
end
